### ISSUE TITLE
README.md contains broken links

### ISSUE THREAD

**Issue by slawr** [aoscloud/aos_communicationmanager#8]
Hi Aos maintainers, 

I found three broken links in the root CM README.md.
I sent PR https://github.com/aoscloud/aos_communicationmanager/pull/7 for the first one. 

The following two I can not fix as I can not be sure what to link to:

1. Link to architecture document.
Source: https://github.com/aoscloud/aos_communicationmanager/blob/fc8fb43c854630ccbb5251946c793d1674d0cde8/README.md?plain=1#L13
I couldn't find architecture.md in the CM component source and there is no doc sub-directory.

2. Link to config.md
Source: https://github.com/aoscloud/aos_communicationmanager/blob/fc8fb43c854630ccbb5251946c793d1674d0cde8/README.md?plain=1#L55

**Comment by Eabramov84** [comment]
Thank you for finding. We will fix it as soos as define documentation storage.

**Comment by Eabramov84** [comment]
Resolved
